---
title: "ordination"
author: "Tobias G Frøslev"
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: yes
    theme: flatly
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
editor_options:
  chunk_output_type: console
---

#### packages ####
```{r, eval=F}
library(here)
library(vegan)
library(readr)
library(dplyr)
```

#### load OTU tables ####
```{r, eval=F}
fun_otu_tab <- readRDS(here::here("data","samples_focussed_otu_tab.RDS")) # taken from the Man vs Machine study: https://github.com/tobiasgf/man_vs_machine/blob/master/data/samples_focussed_otu_tab.RDS
pla_otu_tab <- read.table(here::here("data","plant_table_final.txt"), sep="\t", header = T) # see earlier steps in separate script
euk_raw_derep <- readRDS(here::here("data","euk_raw_derep.RDS"))
ins_raw_derep <- readRDS(here::here("data","ins_raw_derep.RDS"))
```

#### make ordinations ####
```{r, eval=F}
pla_ord <- metaMDS(t(pla_otu_tab[,1:130]), k=6, try=200, trymax = 1000)
fun_ord <- metaMDS(t(fun_otu_tab[,1:130]), k=6, try=200, trymax = 1000)
euk_ord <- metaMDS(t(euk_raw_derep[,1:130]), k=6, try=200, trymax = 1000)
ins_ord <- metaMDS(t(ins_raw_derep[,1:130]), k=6, try=200, trymax = 1000)

col_dat <- data.frame(cbind(pla_ord$points[,1:4],fun_ord$points[,1:4],euk_ord$points[,1:4],ins_ord$points[,1:4]))
names(col_dat) <- c("b_plant1","b_plant2","b_plant3","b_plant4","b_fung1","b_fung2","b_fung3","b_fung4","b_eukar1","b_eukar2","b_eukar3","b_eukar4","b_insect1","b_insect2","b_insect3","b_insect4")

write.table(col_dat, here::here("data","SoilTackerDataforPublication_v2.txt"), sep="\t",quote=FALSE, col.names = NA)
```

#### count of named plant OTUs ####
```{r, eval=F}
pla_otu_tab <- read.table(here::here("data","plant_table_final.txt"), sep="\t", header = T)
pla_otu_tab %>% filter(!grepl("unmatched",species)) %>% filter(!grepl("ambigu",species)) %>% nrow() # 318 unambiguous plant names
```
